base:
  config:
    oauth:
      hostname: localhost
      port: 9001
    nacos:
      hostname: 192.168.62.132
      port: 8848
    rocketmq:
      hostname: 192.168.62.132
      port: 9876

spring:
  application:
    name: cloud-message
  main:
    allow-bean-definition-overriding: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: ${base.config.nacos.hostname}:${base.config.nacos.port}
    # RocketMQ 相关配置
    stream:
      rocketmq:
        binder:
          name-server: ${base.config.rocketmq.hostname}:${base.config.rocketmq.port}
      bindings:
        admin-login-log-topic: {destination: admin-login-log-topic, content-type: application/json}

security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
      access-token-uri: http://${base.config.oauth.hostname}:${base.config.oauth.port}/oauth/token
      user-authorization-uri: http://${base.config.oauth.hostname}:${base.config.oauth.port}/oauth/authorize
    resource:
      token-info-uri: http://${base.config.oauth.hostname}:${base.config.oauth.port}/oauth/check_token

server:
  port: 10002

management:
  endpoints:
    web:
      exposure:
        include: "*"